#!/usr/bin/env bash
# Bash script that creates an RSA key pair.
#     Name of the created private key must be holberton
#     Number of bits in the created key to be created 4096
#     The created key must be protected by the passphrase betty
#     ssh -i ~/.ssh/holberton ubuntu@35.243.157.160

ssh-keygen -t rsa -b 4096 -N "betty" -f school
